export const SET_CLIENT_GOAL = 'SET_CLIENT_GOAL';
export const SET_CLIENT_DATA = 'SET_CLIENT_DATA';
export const SET_CLIENT_SOCKET = 'SET_CLIENT_SOCKET';

export const START_FETCHING_CATEGORIES = 'START_FETCHING_CATEGORIES';
export const FETCHING_CATEGORIES_SUCCEED = 'FETCHING_CATEGORIES_SUCCEED';
export const FETCHING_CATEGORIES_FAILED = 'FETCHING_CATEGORIES_FAILED';

export const START_PLACING_ORDER = 'START_PLACING_ORDER';
export const PLACING_ORDER_SUCCEED = 'PLACING_ORDER_SUCCEED';
export const PLACING_ORDER_FAILED = 'PLACING_ORDER_FAILED';
export const SET_ORDERS = 'SET_ORDERS';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
export const UPDATE_FOOD_TO_BE_ADDED_TO_CART = 'UPDATE_FOOD_TO_BE_ADDED_TO_CART';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAILED = 'AUTH_FAILED'; 

export const SET_ADMIN_DATA = 'SET_ADMIN_DATA';
